config/routes.rb
SalesforceApp::Application.routes.draw do
  resources :users, :only => [:index] do
    resources :coupons, :only => [:create, :destroy]
  end
  
  resources :coupons, :only => [:index]
  
  devise_for :users
  root to: 'roots#root'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  attr_accessible :user_id, :deal_id, :place, :address, :zip, :deal_title, :deal_info
  validates :deal_id, :place, :address, :zip, :deal_title, :deal_info, presence: true
  
  belongs_to :user, :foreign_key => :saved_coupons
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  attr_accessor :saved_coupons
  
  has_many :saved_coupons, :class => "Coupon", :foreign_key => :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include Mobylette::RespondToMobileRequests
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def show
    @coupon = Coupon.find(params[:id])
    respond_to do |format|
      format.html 
      format.json { render json: @coupon }
      format.mobile { render :show }
    end
  end
end

app/controllers/roots_controller.rb
class RootsController < ApplicationController
  def root
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
      format.mobile { render :index }
    end
    # render :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roots_helper.rb
module RootsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/coupons/show.mobile.erb
<div data-role="content">
  <div class="coupon-img">
    <img src="<%= coupon.picture %>">
  </div>
</div>
<div data-role="footer">
  <!-- get coupon -->
  <div data-role="button">
    <%= link_to 'Get Coupon', '#' %>
  </div>
  <!-- save coupon -->
  <div data-role="button">
    <%= link_to 'Save', user_coupons_url %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SalesforceApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <script type="text/javascript"
       src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCglCx9bZ-l_3vXHdN8qkc6pglKSO7W4pY&sensor=true">
   </script>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/application.mobile.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mobile Version!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.mobile.min" %>
  <%= stylesheet_link_tag    "jquery.mobile.min.css" %>

  <%= csrf_meta_tags %>
</head>
<body>
<div data-role="page">
  <%= yield %>
</div>
</body>
</html>

app/views/roots/root.mobile.erb
<div data-role="header">
  <h1>Notes</h1>
</div>
<div id="contentID" class="content">
</div>
<div data-role="content">
</div>

app/views/users/index.mobile.erb
 <div data-role="header">
  <h1>Users</h1>
</div>
<div data-role="content">
  <ul data-role="listview">
  <% @users.each do |user| %>
    <li>
    <%= link_to user do %>
      <h2><%= user.email %></h2>
    <% end %>
    </li>
  <% end %>
  </ul>
</div>
<div data-role="footer">
  <%= link_to 'New user', new_user_registration_url %>
</div>